FLASK_APP=app.py
FLASK_ENV=development
FLASK_RUN_PORT=8000
DATABASE_URL=postgresql://postgres@db/crm
SMTP_EMAIL=your_email@gmail.com
SMTP_PASSWORD=your_email_password
TWILIO_ACCOUNT_SID=your_twilio_account_sid
TWILIO_AUTH_TOKEN=your_twilio_auth_token
TWILIO_PHONE_NUMBER=your_twilio_phone_number



